databases: 
  - name: stockz
    user: stockz
    plan: free
    region: oregon

services: 
  - type: web
    name: stockz
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars: 
      - key: DATABASE_URL
        fromDatabase: 
          name: stockz
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

